name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Voltariuss
website: https://www.dornacraft.fr

main: ${plugin.package}.${project.name}
database: false
api-version: ${minecraft.version}
